name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    name: Rust 1.56.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.56.0
      - run: cargo test --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.56.0
      - run: cargo clippy -- -Dclippy::all
      - run: cargo clippy --tests -- -Dclippy::all

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.56.0
      - run: cargo +1.56.0 fmt --all --check
      - name: Format tests
        run: rustfmt --check tests/**/*.rs
